In [8]:
import pandas as pd
import numpy as np
from mva.inference import *

In [2]:
hbat = pd.DataFrame(pd.read_excel(r"C:\Users\Gazzar\Desktop\Multivariate\15- HBAT Data.xlsx"))


In [3]:
#hbat_test= hbat.loc[:,['x8', 'x13', 'x15']]

In [9]:
#H0: MU = [5,6,7] 
#spherecity_test(hbat_test)
#s_pooled(hbat.loc[:,['x6', 'x13', 'x15']],hbat.loc[:,['x8', 'x12', 'x14']])


(array([[ 2.14594697, -0.41890657,  0.52818434],
        [-0.41890657,  1.76853283,  0.07394495],
        [ 0.52818434,  0.07394495,  1.45058131]]),
 array([[ 1.94959596, -0.86569697,  0.05626263],
        [-0.86569697,  2.38719596,  0.05343434],
        [ 0.05626263,  0.05343434,  2.22919192]]),
 array([[2.34229798, 0.02788384, 1.00010606],
        [0.02788384, 1.1498697 , 0.09445556],
        [1.00010606, 0.09445556, 0.67197071]]))

In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tabulate import  tabulate


def _eigen_decompostion(X, cor = True):
    """
    ..math:: A = Q.lambda.Q^-1
    lambda: eigenvalues in descending oreder
    Q: is normalized eigenvectors
    """
    if cor == True:
        R = X.corr()
        lmbda, Q = np.linalg.eigh(R)

        return lmbda, Q

    else:
        try:
            S = np.cov(X, rowvar=False)
            lmbda, Q = np.linalg.eigh(S)
            return lmbda, Q

        except:
            raise ValueError(f'data matrix must be all numeric')
   
def fit(self, X):
        self.eigenvals, self.eigenvectors = _eigen_decompostion(X, self.cor)
        pass

def summary(lamda):
    """eigenvalues table with % variance explained"""
    pc_list = []
    for i in range(len(lamda)):                    ##indexing each principle component
        pc_list.append("PC"+str(i+1))

    for i in lamda:                              #proportion of variance explained by each principle component
        prop_ex= i/sum(lamda)

    data= {'Principle components':pc_list,
        'Eigen values': lamda,
        'Proportion': prop_ex
        }   
    df= pd.DataFrame(data)
    df['Cumulative'] = df['proportion'].cumsum() ##cumulative proportion of variance explained


    return 

def scree_plot(lamda,n_components):
   #calculate total variance explained by each principal component
    for i in lamda:                              #proportion of variance explained by each principle component
        var_explained = i/sum(lamda)

    pcs=np.arrange(n_components)

    plt.plot(pcs, var_explained, 'o-', linewidth=2, color='blue')
    plt.title('Scree Plot')
    plt.xlabel('Principal Component')
    plt.ylabel('Variance Explained')
    plt.show()

    return








1.0


C:\Users\Gazzar\AppData\Local\Temp/ipykernel_6208/2016475989.py:2: RuntimeWarning: divide by zero encountered in log
  pval = chi2.sf(np.log(0), 3)
